# Generated by Django 4.2.3 on 2023-07-06 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0003_alter_fcuser_options_fcuser_useremail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcuser',
            old_name='useremail',
            new_name='email',
        ),
    ]
